### ISSUE TITLE
Many versions of flux datasources created in ES_store

### ISSUE THREAD

**Issue by brendan-m-murphy** [openghg/openghg#774] opened 2023-09-12 08:57 UTC
### What is your issue?

Some flux files had 2000 - 8700 versions in ES_store.

It looks like files were uploaded in small chunks (e.g. for the flux datasource with 8700 versions, around 7600 different files were uploaded).

See the discussion on PR #751: it is likely that this isn't a bug, but simply that OpenGHG created new versions whenever new data was added to a datasource.

It would be good to find out how the flux files were being added so we can make sure that the changes to versioning behave well in this case. Also, if there were performance issues, it would be useful to recreate this scenario.

It looks like the files were uploaded by Eric in July, for CO2 fluxes with "paris" in the files names. @EricSaboya do you still have the code you used to upload these files, or remember roughly what the process was?

**Comment by brendan-m-murphy** [comment] 2023-09-12 09:01
A related issue: #591. Ideally, we would check if the changes related to that issue fix the "many versions" problem for data that is just being appended to an existing datasource.

**Comment by EricSaboya** [comment] 2023-09-12 09:27
I did add some ~9000 individual flux files with the same key term to this object store. Each file was an hourly CO2 flux for the year 2021. I have since concatenated hourly flux files into monthly flux files which have been added to "co2_europe". I suppose the same problem of multiple versions will appear in "co2_europe" for these flux files. 

Flux files were added with the standardise function in a for-loop cycling through each flux file. I don't have the code any more or the individual files.

Similar to when adding footprint files, it took longer to add each new flux file to the object store. 

NB. I am no longer using ES_store as I thought we had decided to remove this one soon.

**Comment by brendan-m-murphy** [comment] 2023-09-12 09:36
> I did add some ~9000 individual flux files with the same key term to this object store. Each file was an hourly CO2 flux for the year 2021. I have since concatenated hourly flux files into monthly flux files which have been added to "co2_europe". I suppose the same problem of multiple versions will appear in "co2_europe" for these flux files.

Okay, I'll have a look at "co2_europe" to see if the same thing is happening. Could you possibly hold onto the monthly files for a bit, just in case the version problem is still happening?

> Flux files were added with the standardise function in a for-loop cycling through each flux file. I don't have the code any more or the individual files.

Okay thanks. Can you remember if the time periods for the files disjoint? 

> Similar to when adding footprint files, it took longer to add each new flux file to the object store.

That makes sense. There is a change on devel that might help. I think previously, when data was being added to a datasource, all of the existing data was loaded into memory. I think this has been fixed. (It's hard to know for sure because it is hard to test; but it does seem to speed up the existing test suite, which is a good sign.)

> NB. I am no longer using ES_store as I thought we had decided to remove this one soon.

Yes, I don't think anyone is using it except me, and I will stop using it shortly. This issue came up because some code was running slowly on ES_store and the reason turned out to be the large number of versions. Rachel is working on changes that should make versions "smarter", so adding new data doesn't create a new version unless it is overwriting existing data.

Also hopefully we can improve the performance so that it isn't necessary to break the files down so much.

Thanks for the feedback!

**Comment by EricSaboya** [comment] 2023-09-12 10:38
> Okay, I'll have a look at "co2_europe" to see if the same thing is happening. Could you possibly hold onto the monthly files for a bit, just in case the version problem is still happening?

Will keep hold of them! Also, it wouldn't take long to reproduce the individual hourly files if needed

> Okay thanks. Can you remember if the time periods for the files disjoint?

I believe there are no overlapping periods for the files 

>That makes sense. There is a change on devel that might help. I think previously, when data was being added to a datasource, all of the existing data was loaded into memory. I think this has been fixed. (It's hard to know for sure because it is hard to test; but it does seem to speed up the existing test suite, which is a good sign.)

Okay, I'll pull that and see what's happening. I know this is something that has been previously discussed. Agree it's a difficult thing to test. 

>Yes, I don't think anyone is using it except me, and I will stop using it shortly. This issue came up because some code was running slowly on ES_store and the reason turned out to be the large number of versions. Rachel is working on changes that should make versions "smarter", so adding new data doesn't create a new version unless it is overwriting existing data.

I see! Feel free to delete those Paris flux files if you need to, as I said I'm working from the co2_europe store now!

**Comment by rt17603** [comment] 2024-11-15 14:25
Am I correct in saying this was for the old style object store? Are we ok to close this issue or are there things around this that still need to resolved?

**Comment by brendan-m-murphy** [comment] 2024-11-15 14:28
Yes I think the issue is irrelevant now.

**Closed** 2024-11-15 14:30 UTC
Labels: investigate
