### ISSUE TITLE
Add case insensitive attribute checking to `parse_openghg`

### ISSUE THREAD

**Issue by gareth-j** [openghg/openghg#458] opened 2022-10-19 16:07 UTC
Reading some of Alistair's NetCDFs using `standardise..surface.parse_openghg` we're getting errors due to it doing the checks for attributes in a case sensitive way.

**Comment by rt17603** [comment] 2023-01-17 10:45
Need to find examples of Alistair's file for this.

**Comment by SutarPrasad** [comment] 2023-06-28 12:09
Hi @rt17603 @gareth-j, do we have any example files for this to reproduce the bug?

**Comment by rt17603** [comment] 2023-06-28 12:55
I believe Gareth was going to talk to Alistair Manning at the MetOffice about this as he was the one who raised the stated issue - any luck with that @gareth-j?

**Comment by gareth-j** [comment] 2023-06-29 14:31
We should have a look into where the metadata and attributes are lowercased and checked.

**Comment by SutarPrasad** [comment] 2023-06-29 17:03
I looked at the surface.parse_openghg and according to lines 100-107, the check is done in a case-insensitive way using the .lower() function. I also looked at the parse_openghg applied across emissions, surface, and columns.py files and the emissions and columns had this check done in a case-sensitive way.

**Comment by SutarPrasad** [comment] 2023-08-04 08:40
Any further updates on this? Do we need to keep things as it (look at the previous comment)?

**Comment by SutarPrasad** [comment] 2023-08-08 15:42
Discussion from ACRG Architecture: 8 Aug 2023

Unable to reproduce the issue thus it's fine to close.
In future, we might get the same issue from Allaistair and we can look into it, Or Brendan's meta store can come across this issue and can be dealt with then. 

Until then closing it.

**Closed by SutarPrasad** 2023-08-08 15:42 UTC
Labels: bug, high-priority
