### ISSUE TITLE
Bug in `searchResults` dataclass

### ISSUE THREAD

**Issue by gareth-j** [openghg/openghg#153] opened 2021-10-15 17:20 UTC
```
 File "/python/openghg/dataobjects/_searchresults.py", line 41, in __str__\n    
print_strs.extend([f"{sp} at {\', \'.join(self.results[site][sp].keys())}" for sp in species])\n  
File "/python/openghg/dataobjects/_searchresults.py", line 41, in <listcomp>\n    
print_strs.extend([f"{sp} at {\', \'.join(self.results[site][sp].keys())}" for sp in species])\n
TypeError: sequence item 0: expected str instance, int found\n',
```
Found this when creating the Docker image for the dashboard pipeline. Look at the `__str__/__repr__` methods.

**Comment by rt17603** [comment] 2022-09-30 11:19
@gareth-j Is this still a problem? Or has this been fixed now?

**Comment by rt17603** [comment] 2023-01-17 10:22
Unable to reproduce - reopen if needed.

**Closed by rt17603** 2023-01-17 10:22 UTC
Labels: bug, high-priority
